version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_DB=redmine'
  redmine:
    image: redmine:latest
    networks:
      - redmine
    volumes:
      - redmine-data:/usr/src/redmine/files
    ports:
      - 8000:3000
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=123456'
volumes:
  postgres-data:
  redmine-data:
networks:
  redmine:
    driver: bridge
